name: Automatic testing for the Context Lookup

on:
  push:
    branches: [ master ]
    paths: [ 'context-rdf/**' ]
  pull_request:
    paths: [ 'context-rdf/**' ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm ci
        working-directory: ./context-rdf
      - name: Run tests 
        run: npm test
        working-directory: ./context-rdf
